import { useEffect, useState } from 'react'
import './App.css';
import MakeRequest from '../ai/zuki';
import BackButton from "./BackButton";
import RatingPanel from './RatingPanel';
import { useSpotifyApi } from './hooks/useSpotifyApi';

function Rating({genres}) {
  const [ loaded, setLoaded ] = useState(false);
  const [ albumData, setAlbumData ] = useState({});
  const [ conversation, setConversation ] = useState([]);
  const [ gotData, setGotData ] = useState(false);

  useEffect(() => {
    setLoaded(false);

    const message = "You will act as a musical album recommendation tool. I will send a message with a ranking from 1-5 (5 being the best) or a skip for your album suggestion, and you must recommend me another one that I may like. Your response should be in the format: Title; Artist and nothing else. "
    + "I like " + genres.toString() + ", start by recommending me an album. Every suggestion must be an album from the spotify catalogue.";
    sendMessage(message);

    return () => {
      setLoaded(true);
    }

  }, []);

  async function sendMessage(newMessage) {
    setGotData(false);

    // let attempts = 0;
    // while (attempts < 5) {

    //   let newConversation = [...conversation,
    //     { role: 'user', content: newMessage}
    //   ];
  
    //   console.log(attempts);
    //   return MakeRequest(newConversation)
    //   .then(data => {
        
    //     if (data) {
    //       //Add the model's response to conversation
    //       newConversation.push(
    //         { role: 'assistant', content: data}
    //       );
    //       setConversation(newConversation);
    
    //       //Update UI with album info
    //       getSpotify(data);
    //       attempts = 5;
    //     }
        
    //   })
    //   .catch(e => {
    //     console.log(e.message);
    //     console.log('catching error');
    //     attempts++;
    //   })
    // }

  };

  async function getSpotify(albumInfo) {
    //Gets album data given the album and artist generated by spotify
    return GetAlbum(albumInfo)
    .then(data => {
      //There are no albums with multiple credited artists
      setAlbumData({
        image: data.image,
        title: data.title,
        artist: data.artists.name,
      });
    })
    .then(() => setGotData(true))
    .catch(() => {
      return false;
    })
  };

  return (
    <>
      <div className="bg-zinc-800">
        <BackButton></BackButton>
        <div className="flex z-0 justify-center content-center">
          <div className="mt-36">
            <RatingPanel active={gotData} albumData={albumData} onSend={mes => sendMessage(mes)}/>
          </div>
        </div>
      </div>
    </>
  )
}

export default Rating;